### PR TITLE
Support higher versions of react-bootstrap

### PR DESCRIPTION
**Pull request by skylerkatz**
Thank you so much for your package!

I am using your package in a project that includes `react-bootstrap 2.4.x` and it works great. But I have to include `--legacy-peer-deps` to install because it uses a higher version

### CODE REVIEW

**Comment by skylerkatz** [comment]
@jaywilz any chance you and tag a new release for NPM?

Thank so much!

**Comment by jaywilz** [comment]
@skylerkatz I was going to until realising react-bootstrap 2.0.0 introduces breaking changes.

I'll need to spend some time creating a new version, then will release on NPM

**Comment by skylerkatz** [comment]
Thanks for your response.

Let me know if there is anything you would like some help with and I can take a stab at it as well.

**Comment by jaywilz** [comment]
> Let me know if there is anything you would like some help with and I can take a stab at it as well.

There's a draft PR: https://github.com/jaywilz/react-bootstrap-country-select/pull/16

Feel free to contribute, if you fancy it

**Pull request merged**
